name: Build RPM and DEB

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y rpm dpkg-dev

      # ---------- RPM ----------
      - name: Prepare RPM build tree
        run: |
          mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
          tar -czf ~/rpmbuild/SOURCES/file_counter.tar.gz \
              --transform 's|^script/||' \
              script/count_files.sh
          cp rpm/file_counter.spec ~/rpmbuild/SPECS/

 

      - name: Build RPM
        run: |
          rpmbuild -ba ~/rpmbuild/SPECS/file_counter.spec

      # ---------- DEB ----------
      - name: Build DEB
        run: |
          mkdir -p deb/DEBIAN
          mkdir -p deb/usr/local/bin

          cp script/count_files.sh deb/usr/local/bin/count_files.sh
          chmod 755 deb/usr/local/bin/count_files.sh

          cat > deb/DEBIAN/control <<EOF
          Package: file-counter
          Version: 1.0
          Section: utils
          Priority: optional
          Architecture: all
          Maintainer: callacmies <callacmies@gmail.com>
          Description: Count regular files in /etc directory
          EOF

          dpkg-deb --build deb

